name: Botany
main: org.foo_projects.sofar.Botany.Botany
version: 10
softdepend: [Factions, Towny, WorldGuard, Residence]
commands:
    botany:
        aliases: bot
        description: perform various operations
        usage: /botany ...
        permission: botany
        permission-message: You do not have sufficient privileges to do that!
permissions:
    botany:
        description: Gives access to the botany command
        default: op
